#' Organize and Combine imp_detrended_results Files
#'
#' @description Loads, organizes, and combines imp_detrended_results files
#'   produced by MetaMorph and BRASS per the workflow recommended by Cassandra
#'   Baker for analyzing luciferase reporter assays on Arabidopsis thaliana.
#'   Combined data is written to the global environment as a tibble and to the
#'   working directory as a .csv file.
#'
#' @examples \dontrun{
#' luc_organize(names = c("Dull503_1-100.xls", "Dull503_101-200.xls"),
#'      cnd_sheet = "Dull503_.cnd",
#'      zt_lum_sheet = "Sheet1")}
#'
#' @param names Vector of character strings containing the names of
#'   imp_detrended_results files (in the general format "myfile.xls") to be
#'   loaded and organized by the function. The function assumes that these files
#'   are Excel files.
#' @param cnd_sheet Name of the .cnd sheet within each imp_detrended_results
#'   file as a character string. This sheet contains information on the period,
#'   amplitude, phase, and RAE of regions for which period could be assigned. As
#'   this sheet is automatically generated by MetaMorph, the name of this sheet
#'   is typically the same in each file. If the names of these sheets are not
#'   the same, rename the .cnd sheet in each file so that their names are
#'   identical.
#' @param zt_lum_sheet Name of the sheet within each imp_detrended_results file
#'   containing observations on the luminescence values at each ZT time for
#'   individual regions, as a character string. If the names of these sheets are
#'   not the same, rename this sheet in each file so that their names are
#'   identical. This function assumes several characteristics of data within
#'   these sheets, including the following: each row contains data from a
#'   particular region; the first five columns include `File`, `Plate No`,
#'   `Genotype`, `Well / Region`, and `ZT Time`; the `Well / Region` column
#'   contains observations of the general form "ROI '#' Ellipse (Integrated)";
#'   and every column beyond and including the sixth column is a ZT time at
#'   which regions were imaged and the observations within are specific
#'   luminescence values for individual regions.
#'
#' @return A tibble written to the global environment and to the working
#'   directory as a .csv file.
#' @export
luc_organize <- function(names, cnd_sheet, zt_lum_sheet) {
  for (i in 1:length(names)) {
    df <- readxl::read_excel(names[i], sheet = zt_lum_sheet)
    df2 <- df %>%
      dplyr::filter(is.na(`ZT Time`) == T) %>%
      dplyr::select(File, Genotype, Region = `Well / Region`, 6:ncol(df))
    inter <- readxl::read_excel(names[i], sheet = cnd_sheet, range = readxl::cell_cols("J:AR"))
    combine <- inter[1:nrow(df2), ] %>%
      dplyr::select(File = 1, Period, Amplitude, Phase, RAE) %>%
      dplyr::inner_join(df2, by = "File") %>%
      dplyr::select(!File)
    final <- combine[, c(6, 5, seq(1, 4, 1), seq(7, ncol(combine), 1))] %>%
      tidyr::separate(Region, into = c("ROI", "Region", "Ellipse"), sep = "'") %>%
      dplyr::select(!ROI) %>%
      dplyr::select(!Ellipse)
    if (i == 1) {
      output <- final
    } else {
      output <- output %>%
        dplyr::bind_rows(final)
    }
    if (i == length(names)) {
      output$Genotype <- readr::parse_factor(output$Genotype)
      output$Region <- readr::parse_integer(output$Region)
      assign("luc_output", output, envir = rlang::global_env())
      readr::write_csv(output, "All results.csv")
      print("Result saved to global environment as `luc_output` and into working directory as `All results.csv`",
            quote = F)
    }
  }
}

#' Compare Circadian Periods
#'
#' @description Performs two-sample t-test for difference in mean circadian
#'   period between two different families or genotypes using `t.test()`.
#'   `luc_compare()` is designed to work with the data found in `luc_output`,
#'   the data frame produced by `luc_organize()`, although any dataset
#'   containing circadian period and genotype data for individual regions or
#'   entries may be used. Results of the t-test are written to the global
#'   environment.
#'
#' @examples \dontrun{
#' luc_compare(df = luc_output, names = c("Col", "80.1"))}
#'
#' @param df Data frame containing circadian period and genotype data for
#'   individual regions or entries, defaulting to `luc_output`. The function
#'   assumes the existence of `Genotype` and `Period` columns within the data
#'   frame. This data frame may contain data on more genotypes or families than
#'   the two compared by this function.
#' @param names Names of two families or genotypes found within the `Genotype`
#'   column, as a vector of exactly two character strings.
#'
#' @return A list containing the results of the t-test, written to the global
#'   environment. A summary of results is also printed to the console.
#' @export
luc_compare <- function(df = luc_output, names) {
  if (length(names) != 2) {
    stop("`names` argument must be length 2")
  }
  if (names[1] %in% df$Genotype == F) {
    stop("First value of `names` is not present in `Genotype` column of `df`")
  }
  if (names[2] %in% df$Genotype == F) {
    stop("Second value of `names` is not present in `Genotype` column of `df`")
  }
  data <- df %>%
    dplyr::filter(Genotype == ((!! names[1])) | Genotype == ((!! names[2])) )
  test_results <- t.test(data$Period ~ data$Genotype, mu = 0, alternative = "two.sided", conf = 0.95, var.equal = F)
  assign("test_results", test_results, envir = global_env())
  print("Results saved to global environment as `test_results`", quote = F)
  print(paste0("Alternative hypothesis: true difference in mean period between ",
               names[1], " and ", names[2], " is not equal to 0"), quote = F)
  print(paste0("p-value = ", test_results$p.value), quote = F)
  print(test_results$estimate)
}

#' Period/RAE Scatterplot
#'
#' @description Plots period and RAE of individual regions or entries as a
#'   scatterplot faceted by family or genotype, using functions found in
#'   `ggplot2`.`luc_scatter()` is designed to work with the data found in
#'   `luc_output`, the data frame produced by `luc_organize()`, although any
#'   dataset containing circadian period, RAE, region, and genotype data for
#'   individual regions or entries may be used. The plot is printed to the
#'   console and written to the working directory as a .png file. No more than
#'   20 facets may be plotted using this function.
#'
#' @examples \dontrun{
#' luc_scatter(df = luc_output,
#'      title = "Dull 200 Results",
#'      order = c("Col", "19.8", "19.9"),
#'      labels = TRUE)}
#'
#' @param df Data frame containing circadian period, RAE, region, and genotype
#'   data for individual regions or entries, defaulting to `luc_output`. The
#'   function assumes the existence of `Genotype`, `RAE`, `Region`, and `Period`
#'   columns within the data frame.
#' @param title Title of the plot as a character string.
#' @param order Order of genotypes or families within the faceted scatterplot as
#'   a vector of character strings. `luc_scatter()` uses this argument to assign
#'   levels to the `Genotype` column using `factor()`. Accordingly, this
#'   argument must contain all values found within the `Genotype` column,
#'   matched for case, or else some values found in `Genotype` will be erased.
#'   If left as `NA`, the default value, `luc_scatter()` facets the scatterplot
#'   using the default order of values found in the `Genotype` column.
#' @param labels Logical indicating whether to include or exclude region labels
#'   from the plot.
#'
#' @return A faceted scatterplot, printed to the console and written to the
#'   working directory as a .png file.
#' @export
luc_scatter <- function(df = luc_output, title = "Period (hours) vs. RAE", order = NA, labels = T) {
  if (length(summary(df$Genotype)) > 20){
    stop("`luc_scatter()` is designed to plot no more than 20 genotypes/families.
         Please subset `df` so that it contains data for at most 20 genotypes/families.")
  }
  if (length(order) > 1) {
    df$Genotype <- factor(df$Genotype, levels = order)
  }
  img_title <- paste0(title, ".png")
  plot <- ggplot2::ggplot(df, aes(Period, RAE, color = Genotype)) +
    ggplot2::geom_point(size = 1) +
    ggplot2::labs(title = title,
                  x = "period (hours)",
                  y = "RAE",
                  color = "Genotype") +
    ggplot2::scale_color_brewer(palette = "Paired") +
    ggplot2::scale_y_continuous(breaks = seq(0, 1, 0.2)) +
    ggplot2::scale_x_continuous(breaks = seq(0, 200, 2)) +
    ggplot2::geom_hline(yintercept = 0.6, linetype = "dashed", color = "black") +
    ggplot2::theme_bw() +
    ggplot2::coord_cartesian(xlim = c(floor(min(df$Period)) - 1,
                                      ceiling(max(df$Period)) + 1),
                             ylim = c(0, 1)) +
    ggplot2::theme(plot.title = element_text(hjust = 0.5),
                   axis.title = element_text(size = 13),
                   axis.text = element_text(size = 9.5) )
  if (labels == T) {
    plot <- plot + ggplot2::geom_text(aes(label = Region), hjust = 0, vjust = 0, size = 1.2, color = "black")
  }
  if (length(summary(df$Genotype)) %in% seq(1, 5, 1)){
    plot <- plot + ggplot2::facet_wrap(~Genotype, ncol = 1, strip.position = "right")
    print(plot)
    ggplot2::ggsave(img_title, height = 5, width = 5)
  } else if (length(summary(df$Genotype)) %in% seq(6, 10, 1)) {
    plot <- plot + ggplot2::facet_wrap(~Genotype, ncol = 2, strip.position = "right")
    print(plot)
    ggplot2::ggsave(img_title, height = 5, width = 10)
  } else if (length(summary(df$Genotype)) %in% seq(11, 15, 1)) {
    plot <- plot + ggplot2::facet_wrap(~Genotype, ncol = 3, strip.position = "right")
    print(plot)
    ggplot2::ggsave(img_title, height = 5, width = 15)
  } else if (length(summary(df$Genotype)) %in% seq(16, 20, 1)) {
    plot <- plot + ggplot2::facet_wrap(~Genotype, ncol = 4, strip.position = "right")
    print(plot)
    ggplot2::ggsave(img_title, height = 5, width = 20)
  }
  print(paste0("Plot saved to working directory as ", "`", img_title, "`"), quote= F)
}

#' Period Boxplot
#'
#' @description Creates boxplots of circadian period for families or genotypes
#'   using functions found in `ggplot2` and combines them into a single plot.
#'   `luc_boxplot()` is designed to work with the data found in `luc_output`,
#'   the data frame produced by `luc_organize()`, although any dataset
#'   containing circadian period and genotype data for individual regions or
#'   entries may be used. The plot is printed to the console and written to the
#'   working directory as a .png file. Data on no more than 20 families or
#'   genotypes may be plotted using this function.
#'
#' @examples \dontrun{
#' luc_boxplot(df = luc_output,
#'      title = "Dull 1010 Period Distribution",
#'      order = c("Col", "80.8", "90.9"))}
#'
#' @param df Data frame containing circadian period and genotype data for
#'   individual regions or entries, defaulting to `luc_output`. The function
#'   assumes the existence of `Genotype` and `Period` columns within the data
#'   frame.
#' @param title Title of the plot as a character string.
#' @param order Order of genotypes or families within the plot, from top to
#'   bottom, as a vector of character strings. `luc_scatter()` uses this
#'   argument to assign levels to the `Genotype` column using `factor()`.
#'   Accordingly, this argument must contain all values found within the
#'   `Genotype` column, matched for case, or else some values found in
#'   `Genotype` will be erased. If left as `NA`, the default value,
#'   `luc_scatter()` facets the scatterplot using the default order of values
#'   found in the `Genotype` column.
#'
#' @return A plot containing multiple boxplots, printed to the console and
#'   written to the working directory as a .png file.
#' @export
luc_boxplot <- function(df = luc_output, title = "Period (hours) distribution of genotypes",
                        order = NA) {
  if (length(summary(df$Genotype)) > 20){
    stop("`luc_boxplot()` is designed to plot no more than 20 genotypes/families.
         Please subset `df` so that it contains data for at most 20 genotypes/families.")
  }
  if (length(order) > 1) {
    df$Genotype <- factor(df$Genotype, levels = order)
  }
  img_title <- paste0(title, ".png")
  plot <- ggplot2::ggplot(df, aes(Period, Genotype, fill = Genotype)) +
    ggplot2::geom_boxplot(outlier.size = 1) +
    ggplot2::labs(title = title,
                  x = "period (hours)",
                  y = "genotype",
                  fill = "Genotype") +
    ggplot2::scale_fill_brewer(palette = "Paired") +
    ggplot2::scale_x_continuous(breaks = seq(0, 200, 2)) +
    ggplot2::scale_y_discrete(limits = rev(levels(df$Genotype))) +
    ggplot2::theme_bw() +
    ggplot2::coord_cartesian(xlim = c(floor(min(df$Period)) - 1,
                                      ceiling(max(df$Period)) + 1)) +
    ggplot2::theme(plot.title = element_text(hjust = 0.5),
                   axis.title = element_text(size = 13),
                   axis.text = element_text(size = 9.5) )
  print(plot)
  ggplot2::ggsave(img_title, height = length(summary(df$Genotype))/2, width = 6)
  print(paste0("Plot saved to working directory as ", "`", img_title, "`"), quote= F)
}

